// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/cardList/cardList.vue')['default']
    Catalogue: typeof import('./src/components/catalogue/index.vue')['default']
    Dowm_box: typeof import('./src/components/dowm_box/index.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/header/header.vue')['default']
    IEpChatLineSquare: typeof import('~icons/ep/chat-line-square')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpPriceTag: typeof import('~icons/ep/price-tag')['default']
    Lz_card: typeof import('./src/components/lz_card/lz_card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Streaming_cpm: typeof import('./src/components/streaming_cpm/streaming_cpm.vue')['default']
    User_info: typeof import('./src/components/user_info/user_info.vue')['default']
    Website: typeof import('./src/components/website/website.vue')['default']
  }
}

export {}
